stable/apply_it: minor tweaks and add 3.3 kernel

diff --git a/stable/apply_it b/stable/apply_it
--- a/stable/apply_it
+++ b/stable/apply_it
@@ -29,7 +29,15 @@ apply_it ()
 	echo -n "${txtrst}Applying $PATCH to $DIR "
 
 	cd $DIR
+
 	quilt import ../$PATCH &> /dev/null
+	if [ $? -ne 0 ] ; then
+		echo "${txtred} FAILED${txtrst} to import"
+	fi
+
+	# TODO
+	# check for fuzz here much better than we currently do (by hand later)
+	# use something like what 'qp' does?
 	quilt push &> /dev/null
 	if [ $? -ne 0 ] ; then
 		echo "${txtred} FAILED${txtrst}"
@@ -41,10 +49,7 @@ apply_it ()
 }
 
 
+apply_it 3.3
 apply_it 3.2
-#apply_it 3.1
 apply_it 3.0
 #apply_it 2.6.39
-#apply_it 38
-#apply_it 37
-
